# Generated by Django 4.2 on 2023-04-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0006_orderupdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="amount",
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
